config/routes.rb
SsiJobs::Application.routes.draw do
  get "bookmarks/add"
  get "bookmarks/delete"
  devise_for :users
  root :to => 'offers#index'

  get "interviews/index"
  get "interviews/view"
  get "interviews/delete"
  get "offers/index"
  get "offers/search"
  get "offers/view"
  get "offers/delete"
  post "offers/search"
  get "users/sign_out"

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :user
end

app/models/interview.rb
class Interview < ActiveRecord::Base
	belongs_to :offer
end

app/models/offer.rb
class Offer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'flatly'
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def add
  	Bookmark.create(user_id: current_user.id, offer_id: params[:offer_id])
    redirect_to :back
  end

  def delete
  	@bookmark = Bookmark.find(:first, :conditions => ["offer_id = ?", params[:id]])
  	@bookmark.destroy
  	redirect_to :back
  end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController

  before_action :authenticate_user!
  layout 'flatly'

  def index
  end

  def view
  	@id = params[:id]
    @search_phrase = params[:search_phrase]

    @query_name = params[:name]
    @query_category = params[:category]
    @query_job = params[:query_job]
    @query_year = params[:year]

    @offer = Offer.find(:first, :conditions => ["id = ?", @id])
    @interviews = Interview.find(:all, :conditions => ["offer_id = ?", @id])

    #nilガード
    @query_category ||= ""
    @query_job ||= ""
    @query_name ||= ""
    @query_year ||= ""
    @search_phrase ||= ""

    # for sidebar
    @offers = Offer.all


    @categories = []
    @offers.each {|offer| @categories << offer.category}
    @categories.uniq!

    @jobs = []
    @offers.each {|offer| @jobs << offer.job}
    @jobs.uniq!

    @years = []
    @offers.each {|offer| @years << offer.year}
    @years.uniq!
    
    # 履歴に追加
    # redirect_to :controller => "histories", :action => "add", :id => @id unless History.last.offer_id == @id
  end

  def delete
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!
  layout 'flatly'

  def index
    @offers = Offer.all

    @categories = []
    @offers.each {|offer| @categories << offer.category}
    @categories.uniq!
    # @categories = Offer.get_all(:category)

    @jobs = []
    @offers.each {|offer| @jobs << offer.job}
    @jobs.uniq!

    @years = []
    @offers.each {|offer| @years << offer.year}
    @years.uniq!

    @popular_offers = Offer.find(:all, limit: 10)

    @new_offers = @offers.reverse[0..9]
  end

  def search

    @offers = Offer.all

    @categories = []
    @offers.each {|offer| @categories << offer.category}
    @categories.uniq!

    @jobs = []
    @offers.each {|offer| @jobs << offer.job}
    @jobs.uniq!

    @years = []
    @offers.each {|offer| @years << offer.year}
    @years.uniq!

    @histories = Offer.find(:all, :limit => 5, :conditions => ["name like ?", "%NTT%"])

    case request.request_method == "POST"
    when true
      @query_name = "%" + params[:search][:name] + "%"

       #もし検索元がbreadcrumbだったら
      @re_search = params[:id]

      @query_category = params[:category] or ""
      @query_job = params[:job] or ""
      @query_year = params[:year] or ""
    when false
      @query_category = params[:category]
      @query_job = params[:job]
    end

    @sql =""
    @conditions = []

    unless @query_name == ""
      if @sql.empty?
        @sql += "name like ?"
        @conditions << @query_name
      else
        @sql += " and name like ?"
        @conditions << @query_name
      end
    end

    unless @query_category == ""
      if @sql.empty?
        @sql += "category like ?"
        @conditions << @query_category
      else
        @sql += " and category like ?"
        @conditions << @query_category
      end
    end

    unless @query_job == ""
      if @sql.empty?
        @sql += "job like ?"
        @conditions << @query_job
      else
        @sql += " and job like ?"
        @conditions << @query_job
      end
    end

    unless @query_year == ""
      if @sql.empty?
        @sql += "year like ?"
        @conditions << @query_year
      else
        @sql += " and year like ?"
        @conditions << @query_year
      end
    end

    @conditions.insert(0, @sql)

    # POSTで検索するのをクイックサーチだけに絞る
    @results = Offer.find(:all, :conditions => ["name like ?", @query_name])

    # GETで検索されたとき（左サイドバー）
    unless request.request_method == "POST"

      # nilガード
      @query_job ||= ""
      @query_category ||= ""

      @results = Offer.find(:all, :conditions => ["category like ? or job like ?", @query_category, @query_job])
    end

    #もし検索元がヘッダーの検索窓（クイックサーチ）だったら
    @quick_search = params[:search]

    #もし検索元がbreadcrumbだったら
    @results = Offer.find(:all, :conditions => ["name like ? and category like ? and job like ? and year like ?", @query_name, @query_category, @query_job, @query_year]) if params[:id] == "re_search"

    #breadcrumbの表示のために、%を除く
    @query_name = @query_name[1..@query_name.size-2] if request.request_method == "POST"

  end

  def view
  end

  def delete
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/bookmarks/add.html.erb
<h1>Bookmarks#add</h1>
<p>Find me in app/views/bookmarks/add.html.erb</p>

app/views/bookmarks/delete.html.erb
<h1>Bookmarks#delete</h1>
<p>Find me in app/views/bookmarks/delete.html.erb</p>

app/views/interviews/delete.html.erb
<h1>Interviews#delete</h1>
<p>Find me in app/views/interviews/delete.html.erb</p>

app/views/interviews/index.html.erb
<h1>Interviews#index</h1>
<p>Find me in app/views/interviews/index.html.erb</p>

app/views/interviews/view.html.erb
<!-- model Interview user_id:integer ordinal:string interviewer:string distance:string desk_presence:string atomosphere:string others:string question:string impression:string offer_id:integer -->



<style>
   #content {
    background: #f5f5f5;
   }

   .result {
    width: 80%;
    background: white;
   }


   /*
   .interview {
    border: ridge 10px mediumseagreen;
    background: lightgreen;
   }
  */
   #mytable {
      width:700px;
      margin-left: 2%; 
      margin-bottom: 5%;
      padding:0;
      border:0;
      border-spacing:0;
      border-collapse:collapse;
  }
  caption {
      padding:0 0 0 0;
      font:italic 11px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;
      text-align:right;
  }
  th {
      font:bold 11px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;
      color:#4f6b72;
      border:1px solid #c1dad7;
      letter-spacing:2px;
      text-transform:uppercase;
      text-align:left;
      padding:6px 6px 6px 12px;
      background:#cae8ea url("img/bg_header.jpg") no-repeat;
      min-width: 100px;
  }
  th.nobg {
      border-top:0;
      border-left:0;
      background:none;
  }
  td {
      border:1px solid #c1dad7;
      background:#fff;
      padding:6px 6px 6px 12px;
      /*color:#4f6b72;*/
  }

  .result {
    width: 65%;
  }

  .interview-header {
    background: red;
  }
  /*
  td.alt {
      background:#F5FAFA;
      /*color:#797268;*/
  }
  /*
  th.spec {
      background:#fff url("img/bullet1.gif") no-repeat;
      font:bold 10px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;
  }
  th.specalt {
      background:#f5fafa url("img/bullet2.gif") no-repeat;
      font:bold 10px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;
      color:#797268;
  }
  */
  
</style>


<div class="container">
      <div class="row">

        <ol class="breadcrumb">
        	<% @search_phrase ||= "" %>
            <li><%= link_to "Home", :controller => "offers", :action => "index" %></a></li>
            <li><%= link_to "「" + @search_phrase  + "」の検索結果", :controller => "offers", :action => "search", :name => @query_name, :category => @query_category, :job => @query_job, :year => @query_year, :id => "re_search"  %></li>
            <li><%= @offer.name %> <%= @offer.job %></li>
          </ol>
        
        <div class="panel panel-warning result">
            <div class="panel-heading interview-header">
              <h3 class="panel-title"><%= @offer.name %>　<%= @offer.year %>年度　<%= @offer.job %><span style="margin-left:8%; font-size:15px;"><%= link_to "ブックマークに追加", :controller => "bookmarks", :action => "add", :offer_id => @offer.id %></span></h3>
            </div>
              <div class="panel-body">
                <div class ="interview">
		            <% @interviews.each do |interview| %>
	                  <h3><%= interview.ordinal %>次選考</h3><br>
		              <table id="mytable">
		                <tr>
		                  <th scope="col">形式</th>
		                  <td><%= interview.interviewer %></td>
		                </tr>
		                <tr>
		                  <th scope="col">距離</th>
		                  <td class="alt"><%= interview.distance %></td>
		                </tr>
		                <tr>
		                  <th scope="col">机の有無</th>
		                  <td><%= interview.desk_presence %></td>
		                </tr>
		                <tr>
		                  <th scope="col">雰囲気</th>
		                  <td class="alt"><%= interview.atomosphere %></td>
		                </tr>
		                <tr>
		                  <th scope="col">質問内容</th>
		                  <td><%= interview.question %></td>
		                </tr>
		                <tr>
		                  <th scope="col">感想</th>
		                  <td class="alt"><%= interview.impression %></td>
		                </tr>
		              </table>
		            <% end %>
         </div>


              </div>
          </div>
       </div>
    </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SsiJobs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Bootswatch</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Themes <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="themes">
                <li><a href="../default/">Default</a></li>
                <li class="divider"></li>
                <li><a href="../amelia/">Amelia</a></li>
                <li><a href="../cerulean/">Cerulean</a></li>
                <li><a href="../cosmo/">Cosmo</a></li>
                <li><a href="../cyborg/">Cyborg</a></li>
                <li><a href="../flatly/">Flatly</a></li>
                <li><a href="../journal/">Journal</a></li>
                <li><a href="../lumen/">Lumen</a></li>
                <li><a href="../readable/">Readable</a></li>
                <li><a href="../simplex/">Simplex</a></li>
                <li><a href="../slate/">Slate</a></li>
                <li><a href="../spacelab/">Spacelab</a></li>
                <li><a href="../superhero/">Superhero</a></li>
                <li><a href="../united/">United</a></li>
                <li><a href="../yeti/">Yeti</a></li>
              </ul>
            </li>
            <li>
              <a href="../help/">Help</a>
            </li>
            <li>
              <a href="http://news.bootswatch.com">Blog</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Download <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a href="./bootstrap.min.css">bootstrap.min.css</a></li>
                <li><a href="./bootstrap.css">bootstrap.css</a></li>
                <li class="divider"></li>
                <li><a href="./variables.less">variables.less</a></li>
                <li><a href="./bootswatch.less">bootswatch.less</a></li>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><a href="http://builtwithbootstrap.com/" target="_blank">Built With Bootstrap</a></li>
            <li><a href="https://wrapbootstrap.com/?ref=bsw" target="_blank">WrapBootstrap</a></li>
          </ul>

        </div>
      </div>
    </div>
    
<%= yield %>

</body>
</html>

app/views/layouts/flatly.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ssi_jobs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "flatly", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  <style>
    body {
      background: #f5f5f5;
    }

    .row {
      /*min-width: 66%;*/
    }

    .col-md-8 {
      min-width: 66%;
    }

    nav {
      margin-top: 60px;
    }



  .panel-body {
    border-bottom: 1px solid #d3d3d3;
  }

  #modal {
    vertical-align: center;
  }

  .breadcrumb{
  width: 65%;
  background: white;
 }

 .quick-search, .search-btn {
  margin-top: 4%;
 }

 #modal, #title > a {
  color: white;
 }

 #user {
  color: white;
  margin-top: 1.2em;
 }

#title {
  font-size: 28px;
  margin-top: 2px;
}

.user-icon {
  height: 1.8em;
  width: 1.8em;
  margin-top: 1em;
  margin-right: 0.5em;
}

#quick_search {
  margin-top: 2px;
}

.navbar {
  height: 50px;
}

#login, #logout {
  margin-top: 2px;
}

</style>
</head>
<body>

  <!--ヘッダー-->
  <!-- Static navbar -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand" id="title">
          <%= link_to "SSI jobs", root_path %>
          </div>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <!--クイック検索-->
            <li><%= form_tag(offers_search_path, :class => "navbar-form navbar-left", :role => "search", :id => "quick_search") do %>
              <div id="form-group" class="col-xs-9 quick-search"><%= text_field( :search, :name, :placeholder => "会社名で検索", :class => "form-control") %></div><%= submit_tag("検索", :class => "btn btn-danger search-btn") %>
            <% end %>
          </li>



            <!--詳細検索-->
            <!--Modal-->
        <!--
        <li><button data-toggle="modal" data-target="#myModal" class="btn" id="modal">詳細検索</button></li>
        <div class="modal fade" id="myModal">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color:black;">What is Emeco ?</h4>
              </div>
              <div class="modal-body">
                hogehoge
              </div>
              <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">OK!</button>
              </div>
            </div>
          </div>
        </div>
      -->



          </ul>
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- 改善アイデア -->
      <!-- 年収の目安で検索できる ->
      <!-- 地域から検索できる -->
      <!-- オフィスの様子 -->
      <!-- 最寄り駅、通勤の便、車通勤ok? -->
      <!-- 社員人数 -->
      <!-- 株価、財務諸表 -->
      <!-- 研修、最初の仕事 -->
      <!-- ノルマ的な -->
      <!-- 就活エピソード -->
      <!-- 出張、転勤がある？ -->
      <!-- OBに働いてる所感を聴いてみる -->
      <!-- 社員食堂 -->


    <!--ここからボディー-->
  <div class="container">
    <div class="row">

      <!--左サイドバー-->
      <div class="col-md-2">

        <!--業界-->
        <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">業界</h3>
            </div>

            <!--nilガード-->
            <% @categories ||= [] %>
            <% @categories.each do |category| %>
              <div class="panel-body"><%= link_to category, :controller => "offers", :action => "search", :method => "POST", :category => category %></div>
            <% end %>
          </div>

          <!--職種-->
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">職種</h3>
            </div>

            <!--nilガード-->
            <% @jobs ||= [] %>

            <% @jobs.each do |job| %>
              <div class="panel-body"><%= link_to job, :controller => "offers", :action => "search", :method => "POST", :job => job %></div>
            <% end %>
          </div>

      </div>
      <!--ここまでサイドバー-->

      <div class="col-md-8">
        <% if notice %>
          <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-error"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>

      <!--ここから左サイドバー-->
      <div class="col-md-2">

        <!--ブックマーク-->

        <% @bookmarks = []
              if current_user.present?
                @user_id = current_user.id
                @bookmark_ids = Bookmark.find(:all, conditions: ["user_id = ?", current_user.id])
                @bookmark_ids.each do |bookmark|
                @bookmarks << Offer.find_by_id(bookmark.offer_id)
                end 
              end %>
          
        <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">ブックマーク</h3>
            </div>

            <!--nilガード-->
            <% @bookmarks ||= [] %>

            <% @bookmarks.each do |bookmark| %>
            <div class="panel-body"><%= link_to bookmark.name, :controller => "interviews", :action => "view", :id => bookmark.id  %>
            <span id="bookmark-delete" style="float:right"><%= link_to "×", :controller => "bookmarks", :action => "delete", :id => bookmark.id  %></span>
            </div>
            <% end %>
        </div>

      </div>

    </div>
  </div><!--.container-->

    <div id="footer" class="container" style="height: 5%;"></div>
 
</body>
</html>

app/views/layouts/united.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ssi_jobs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "united", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  <style>
    body {
      margin-top: 60px;
      background: #f5f5f5;
    }

  .panel-body {
    border-bottom: 1px solid #d3d3d3;
  }

  #modal {
    vertical-align: center;
  }

  .breadcrumb{
  width: 65%;
  background: white;
 }

 .quick-search, .search-btn {
  margin-top: 4%;
 }

 #modal, #title > a {
  color: white;
 }

 #user {
  color: white;
  margin-top: 1.2em;
 }

#title {
  font-size: 28px;
  margin-top: 2px;
}

.user-icon {
  height: 1.8em;
  width: 1.8em;
  margin-top: 1em;
  margin-right: 0.5em;
}

#quick_search {
  margin-top: 2px;
}

.navbar {
  height: 50px;
}

#login, #logout {
  margin-top: 2px;
}

</style>
</head>
<body>

  <!--ヘッダー-->
  <!-- Static navbar -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand" id="title">
          <%= link_to "SSI jobs", root_path %>
          </div>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <!--クイック検索-->
            <li><%= form_tag(offers_search_path, :class => "navbar-form navbar-left", :role => "search", :id => "quick_search") do %>
              <div id="form-group" class="col-xs-9 quick-search"><%= text_field( :search, :name, :placeholder => "会社名で検索", :class => "form-control") %></div><%= submit_tag("検索", :class => "btn btn-primary search-btn") %>
            <% end %>
          </li>



            <!--詳細検索-->
            <!--Modal-->
        <!--
        <li><button data-toggle="modal" data-target="#myModal" class="btn" id="modal">詳細検索</button></li>
        <div class="modal fade" id="myModal">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="color:black;">What is Emeco ?</h4>
              </div>
              <div class="modal-body">
                hogehoge
              </div>
              <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">OK!</button>
              </div>
            </div>
          </div>
        </div>
      -->



          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= image_tag "user.png", :class => "user-icon" %></li>
          <% if false %>
            <% if user_signed_in? %>
              <li id="user"><%= current_user.email %></li>
              <li id="login"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li id="logout"><%= link_to "ログイン", new_user_session_path %></li>
            <% end %>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- 改善アイデア -->
      <!-- 年収の目安で検索できる ->
      <!-- 地域から検索できる -->
      <!-- オフィスの様子 -->
      <!-- 最寄り駅、通勤の便、車通勤ok? -->
      <!-- 社員人数 -->
      <!-- 株価、財務諸表 -->
      <!-- 研修、最初の仕事 -->
      <!-- ノルマ的な -->
      <!-- 就活エピソード -->
      <!-- 出張、転勤がある？ -->
      <!-- OBに働いてる所感を聴いてみる -->
      <!-- 社員食堂 -->


    <!--ここからボディー-->
  <div class="container">
    <div class="row">

      <!--左サイドバー-->
      <div class="col-md-2">

        <!--業界-->
        <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">業界</h3>
            </div>

            <!--nilガード-->
            <% @categories ||= [] %>
            <% @categories.each do |category| %>
              <div class="panel-body"><%= link_to category, :controller => "offers", :action => "search", :method => "POST", :category => category %></div>
            <% end %>
          </div>

          <!--職種-->
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">職種</h3>
            </div>

            <!--nilガード-->
            <% @jobs ||= [] %>

            <% @jobs.each do |job| %>
              <div class="panel-body"><%= link_to job, :controller => "offers", :action => "search", :method => "POST", :job => job %></div>
            <% end %>
          </div>

      </div>
      <!--ここまでサイドバー-->

      <div class="col-md-8">
        <%= yield %>
      </div>

      <!--ここから左サイドバー-->
      <div class="col-md-2">

        <!--ブックマーク-->

        <% if false %>
        <% @bookmarks = []
              if current_user.present?
                @user_id = current_user.id
                @bookmark_ids = Bookmark.find(:all, conditions: ["user_id = ?", current_user.id])
                @bookmark_ids.each do |bookmark|
                @bookmarks << Offer.find_by_id(bookmark.offer_id)
                end 
              end %>
          %>
          <% end%>
        <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">ブックマーク</h3>
            </div>

            <!--nilガード-->
            <% @bookmarks ||= [] %>

            <% @bookmarks.each do |bookmark| %>
            <div class="panel-body"><%= link_to bookmark.name, :controller => "interviews", :action => "view", :id => bookmark.id  %></div>
            <% end %>
        </div>

      </div>

    </div>
  </div><!--.container-->

    <div id="footer" class="container" style="height: 5%;"></div>
 
</body>
</html>

app/views/offers/delete.html.erb
<h1>Offers#delete</h1>
<p>Find me in app/views/offers/delete.html.erb</p>

app/views/offers/view.html.erb
<h1>Offers#view</h1>
<p>Find me in app/views/offers/view.html.erb</p>